### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by jaekit** [jaekit/brackeys#8]
- [x] Update levels based on playtest
- [x] jellyfish sprite
- [x] dash item indicator when available
- [x] big death sprite
